// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLE_zkFiDnGzSDRb00ipPOW4pqvUDa1fM',
    appId: '1:920232060302:web:32aefdd55ff0aa474130df',
    messagingSenderId: '920232060302',
    projectId: 'twitterclone-12345',
    authDomain: 'twitterclone-12345.firebaseapp.com',
    storageBucket: 'twitterclone-12345.appspot.com',
    measurementId: 'G-FVGD25KT7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWIzcs2GLQGaGxEROqr92ZXorlKoHoI6M',
    appId: '1:920232060302:android:724a6d80f377c1ae4130df',
    messagingSenderId: '920232060302',
    projectId: 'twitterclone-12345',
    storageBucket: 'twitterclone-12345.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgjce66DFCZoSAOy38TvDsb1V7dypaeA8',
    appId: '1:920232060302:ios:881d35f0811dbbc14130df',
    messagingSenderId: '920232060302',
    projectId: 'twitterclone-12345',
    storageBucket: 'twitterclone-12345.appspot.com',
    iosBundleId: 'com.example.twitterclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgjce66DFCZoSAOy38TvDsb1V7dypaeA8',
    appId: '1:920232060302:ios:881d35f0811dbbc14130df',
    messagingSenderId: '920232060302',
    projectId: 'twitterclone-12345',
    storageBucket: 'twitterclone-12345.appspot.com',
    iosBundleId: 'com.example.twitterclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLE_zkFiDnGzSDRb00ipPOW4pqvUDa1fM',
    appId: '1:920232060302:web:f2783efbcc725e7d4130df',
    messagingSenderId: '920232060302',
    projectId: 'twitterclone-12345',
    authDomain: 'twitterclone-12345.firebaseapp.com',
    storageBucket: 'twitterclone-12345.appspot.com',
    measurementId: 'G-VQ1VDPV11R',
  );
}
